### ISSUE TITLE
One physical controller is duplicated 

### ISSUE THREAD

**Issue by seeseekey** [ChimeraOS/chimeraos#1033]
I am using the current version ChimeraOS 46-2 with two Xbox Series X controllers. If I connect the first controller, I see one controller in the Steam controller settings. If I connect the second controller, it is duplicated (so three controller in total).

The second controller, for example, emits two button presses for players 2 and 3 when I press one button on the physical controller.

For testing, I disabled input plumber:

```bash
sudo systemctl disable inputplumber
```

After a restart, the controllers work normally -> two physical controllers -> two controllers in the game/Steam settings.

**Comment by AlasdairWallaceMackie** [comment]
I've been having a similar issue with a single Xbox Series X controller. It often double inputs in the menus. When I go to the main side menu and select 'Power', it double inputs and chooses 'Sleep', without giving me the option to choose 'Shut Down'

**Comment by sboulkour** [comment]
Same issue here, having a unique Xbox controller being displayed and behaving like two (double button press etc).

Disabling/enabling Bluetooth used to fix the issue after each boot. But for a day or two, the controller is never detected as unique anymore.

**Comment by alkazar** [comment]
This should be fixed in the latest release.

**Comment by thekk1** [comment]
This issue is not fixed.
ChimerOS 49-1.
Disable inputplumber service fixed the double controller problem.

**Comment by alkazar** [comment]
That is possible, but my main gaming machine has been running ChimeraOS for 4 years and I do not experience this. Very strange.

I do not use PS4 controllers though, so maybe that is something.

What is the output of the following commands:
- `inputplumber devices list`
- `inputplumber sources list`
- `inputplumber targets list`

**Comment by thekk1** [comment]
[gamer@Zocki ~]$ inputplumber devices list
╭────────┬──────────╮
│ Composite Devices │
├────────┼──────────┤
│ Id     │ Name     │
╰────────┴──────────╯
Found 0 composite device(s)
[gamer@Zocki ~]$ inputplumber sources list
╭────────────────────┬────────────────────────────────────────┬───────────╮
│ Source Devices                                                          │
├────────────────────┼────────────────────────────────────────┼───────────┤
│ path               │ name                                   │ subsystem │
├────────────────────┼────────────────────────────────────────┼───────────┤
│ /dev/input/event0  │ Power Button                           │ input     │
├────────────────────┼────────────────────────────────────────┼───────────┤
│ /dev/input/event1  │ Video Bus                              │ input     │
├────────────────────┼────────────────────────────────────────┼───────────┤
│ /dev/input/event10 │ Logitech USB Receiver                  │ input     │
├────────────────────┼────────────────────────────────────────┼───────────┤
│ /dev/input/event11 │ HD-Audio Generic HDMI/DP,pcm=3         │ input     │
├────────────────────┼────────────────────────────────────────┼───────────┤
│ /dev/input/event12 │ PC Speaker                             │ input     │
├────────────────────┼────────────────────────────────────────┼───────────┤
│ /dev/input/event13 │ HD-Audio Generic HDMI/DP,pcm=7         │ input     │
├────────────────────┼────────────────────────────────────────┼───────────┤
│ /dev/input/event14 │ HD-Audio Generic HDMI/DP,pcm=8         │ input     │
├────────────────────┼────────────────────────────────────────┼───────────┤
│ /dev/input/event15 │ HD-Audio Generic HDMI/DP,pcm=9         │ input     │
├────────────────────┼────────────────────────────────────────┼───────────┤
│ /dev/input/event16 │ Logitech USB Receiver                  │ input     │
├────────────────────┼────────────────────────────────────────┼───────────┤
│ /dev/input/event17 │ HD-Audio Generic Mic                   │ input     │
├────────────────────┼────────────────────────────────────────┼───────────┤
│ /dev/input/event18 │ HD-Audio Generic Headphone             │ input     │
├────────────────────┼────────────────────────────────────────┼───────────┤
│ /dev/input/event19 │ Wireless Controller                    │ input     │
├────────────────────┼────────────────────────────────────────┼───────────┤
│ /dev/input/event2  │   Mini Keyboard                        │ input     │
├────────────────────┼────────────────────────────────────────┼───────────┤
│ /dev/input/event20 │ Wireless Controller Motion Sensors     │ input     │
├────────────────────┼────────────────────────────────────────┼───────────┤
│ /dev/input/event21 │ Wireless Controller Touchpad           │ input     │
├────────────────────┼────────────────────────────────────────┼───────────┤
│ /dev/input/event28 │ Wireless Controller                    │ input     │
├────────────────────┼────────────────────────────────────────┼───────────┤
│ /dev/input/event29 │ Wireless Controller Motion Sensors     │ input     │
├────────────────────┼────────────────────────────────────────┼───────────┤
│ /dev/input/event3  │   Mini Keyboard Mouse                  │ input     │
├────────────────────┼────────────────────────────────────────┼───────────┤
│ /dev/input/event30 │ Wireless Controller Touchpad           │ input     │
├────────────────────┼────────────────────────────────────────┼───────────┤
│ /dev/input/event4  │   Mini Keyboard System Control         │ input     │
├────────────────────┼────────────────────────────────────────┼───────────┤
│ /dev/input/event5  │   Mini Keyboard Consumer Control       │ input     │
├────────────────────┼────────────────────────────────────────┼───────────┤
│ /dev/input/event6  │ Logitech USB Receiver                  │ input     │
├────────────────────┼────────────────────────────────────────┼───────────┤
│ /dev/input/event7  │ Logitech USB Receiver Mouse            │ input     │
├────────────────────┼────────────────────────────────────────┼───────────┤
│ /dev/input/event8  │ Logitech USB Receiver Consumer Control │ input     │
├────────────────────┼────────────────────────────────────────┼───────────┤
│ /dev/input/event9  │ Logitech USB Receiver System Control   │ input     │
├────────────────────┼────────────────────────────────────────┼───────────┤
│ /dev/hidraw0       │ Mini Keyboard                          │ hidraw    │
├────────────────────┼────────────────────────────────────────┼───────────┤
│ /dev/hidraw1       │ Mini Keyboard Consumer Control         │ hidraw    │
├────────────────────┼────────────────────────────────────────┼───────────┤
│ /dev/hidraw2       │ Logitech USB Receiver                  │ hidraw    │
├────────────────────┼────────────────────────────────────────┼───────────┤
│ /dev/hidraw3       │ Logitech USB Receiver System Control   │ hidraw    │
├────────────────────┼────────────────────────────────────────┼───────────┤
│ /dev/hidraw4       │                                        │ hidraw    │
├────────────────────┼────────────────────────────────────────┼───────────┤
│ /dev/hidraw5       │ Logitech USB Receiver                  │ hidraw    │
├────────────────────┼────────────────────────────────────────┼───────────┤
│ /dev/hidraw6       │ Wireless Controller Touchpad           │ hidraw    │
├────────────────────┼────────────────────────────────────────┼───────────┤
│ /dev/hidraw8       │ Wireless Controller Motion Sensors     │ hidraw    │
├────────────────────┼────────────────────────────────────────┼───────────┤
│                    │ Power Button                           │ input     │
├────────────────────┼────────────────────────────────────────┼───────────┤
│                    │ Video Bus                              │ input     │
├────────────────────┼────────────────────────────────────────┼───────────┤
│                    │ Logitech USB Receiver                  │ input     │
├────────────────────┼────────────────────────────────────────┼───────────┤
│                    │ PC Speaker                             │ input     │
├────────────────────┼────────────────────────────────────────┼───────────┤
│                    │ HD-Audio Generic HDMI/DP,pcm=3         │ input     │
├────────────────────┼────────────────────────────────────────┼───────────┤
│                    │ HD-Audio Generic HDMI/DP,pcm=7         │ input     │
├────────────────────┼────────────────────────────────────────┼───────────┤
│                    │ HD-Audio Generic HDMI/DP,pcm=8         │ input     │
├────────────────────┼────────────────────────────────────────┼───────────┤
│                    │ HD-Audio Generic HDMI/DP,pcm=9         │ input     │
├────────────────────┼────────────────────────────────────────┼───────────┤
│                    │ Logitech USB Receiver                  │ input     │
├────────────────────┼────────────────────────────────────────┼───────────┤
│                    │ HD-Audio Generic Mic                   │ input     │
├────────────────────┼────────────────────────────────────────┼───────────┤
│                    │ HD-Audio Generic Headphone             │ input     │
├────────────────────┼────────────────────────────────────────┼───────────┤
│                    │   Mini Keyboard                        │ input     │
├────────────────────┼────────────────────────────────────────┼───────────┤
│                    │ Wireless Controller                    │ input     │
├────────────────────┼────────────────────────────────────────┼───────────┤
│                    │ Wireless Controller Touchpad           │ leds      │
├────────────────────┼────────────────────────────────────────┼───────────┤
│                    │ Wireless Controller Touchpad           │ leds      │
├────────────────────┼────────────────────────────────────────┼───────────┤
│                    │ Wireless Controller Touchpad           │ leds      │
├────────────────────┼────────────────────────────────────────┼───────────┤
│                    │ Wireless Controller Touchpad           │ leds      │
├────────────────────┼────────────────────────────────────────┼───────────┤
│                    │ Wireless Controller Motion Sensors     │ input     │
├────────────────────┼────────────────────────────────────────┼───────────┤
│                    │ Wireless Controller Touchpad           │ input     │
├────────────────────┼────────────────────────────────────────┼───────────┤
│                    │ Wireless Controller                    │ input     │
├────────────────────┼────────────────────────────────────────┼───────────┤
│                    │ Wireless Controller Motion Sensors     │ leds      │
├────────────────────┼────────────────────────────────────────┼───────────┤
│                    │ Wireless Controller Motion Sensors     │ leds      │
├────────────────────┼────────────────────────────────────────┼───────────┤
│                    │ Wireless Controller Motion Sensors     │ leds      │
├────────────────────┼────────────────────────────────────────┼───────────┤
│                    │ Wireless Controller Motion Sensors     │ leds      │
├────────────────────┼────────────────────────────────────────┼───────────┤
│                    │   Mini Keyboard                        │ leds      │
├────────────────────┼────────────────────────────────────────┼───────────┤
│                    │   Mini Keyboard                        │ leds      │
├────────────────────┼────────────────────────────────────────┼───────────┤
│                    │   Mini Keyboard                        │ leds      │
├────────────────────┼────────────────────────────────────────┼───────────┤
│                    │   Mini Keyboard                        │ leds      │
├────────────────────┼────────────────────────────────────────┼───────────┤
│                    │   Mini Keyboard                        │ leds      │
├────────────────────┼────────────────────────────────────────┼───────────┤
│                    │   Mini Keyboard Mouse                  │ input     │
├────────────────────┼────────────────────────────────────────┼───────────┤
│                    │ Wireless Controller Motion Sensors     │ input     │
├────────────────────┼────────────────────────────────────────┼───────────┤
│                    │ Wireless Controller Touchpad           │ input     │
├────────────────────┼────────────────────────────────────────┼───────────┤
│                    │ Microsoft X-Box 360 pad 1              │ input     │
├────────────────────┼────────────────────────────────────────┼───────────┤
│                    │   Mini Keyboard System Control         │ input     │
├────────────────────┼────────────────────────────────────────┼───────────┤
│                    │   Mini Keyboard Consumer Control       │ input     │
├────────────────────┼────────────────────────────────────────┼───────────┤
│                    │ Logitech USB Receiver                  │ input     │
├────────────────────┼────────────────────────────────────────┼───────────┤
│                    │ Logitech USB Receiver                  │ leds      │
├────────────────────┼────────────────────────────────────────┼───────────┤
│                    │ Logitech USB Receiver                  │ leds      │
├────────────────────┼────────────────────────────────────────┼───────────┤
│                    │ Logitech USB Receiver                  │ leds      │
├────────────────────┼────────────────────────────────────────┼───────────┤
│                    │ Logitech USB Receiver                  │ leds      │
├────────────────────┼────────────────────────────────────────┼───────────┤
│                    │ Logitech USB Receiver                  │ leds      │
├────────────────────┼────────────────────────────────────────┼───────────┤
│                    │ Logitech USB Receiver Mouse            │ input     │
├────────────────────┼────────────────────────────────────────┼───────────┤
│                    │ Logitech USB Receiver Consumer Control │ input     │
├────────────────────┼────────────────────────────────────────┼───────────┤
│                    │ Logitech USB Receiver System Control   │ input     │
├────────────────────┼────────────────────────────────────────┼───────────┤
│ /dev/input/js0     │ Wireless Controller                    │ input     │
├────────────────────┼────────────────────────────────────────┼───────────┤
│ /dev/input/js4     │ Wireless Controller                    │ input     │
├────────────────────┼────────────────────────────────────────┼───────────┤
│ /dev/input/mice    │                                        │ input     │
├────────────────────┼────────────────────────────────────────┼───────────┤
│ /dev/input/mouse0  │   Mini Keyboard Mouse                  │ input     │
├────────────────────┼────────────────────────────────────────┼───────────┤
│ /dev/input/mouse1  │ Logitech USB Receiver Mouse            │ input     │
├────────────────────┼────────────────────────────────────────┼───────────┤
│ /dev/input/mouse2  │ Logitech USB Receiver                  │ input     │
├────────────────────┼────────────────────────────────────────┼───────────┤
│ /dev/input/mouse3  │ Wireless Controller Touchpad           │ input     │
├────────────────────┼────────────────────────────────────────┼───────────┤
│ /dev/input/mouse6  │ Wireless Controller Touchpad           │ input     │
╰────────────────────┴────────────────────────────────────────┴───────────╯
Found 85 source device(s)
[gamer@Zocki ~]$ inputplumber targets list
╭────────────────╮
│ Target Devices │
├────────────────┤
│ DBus Path      │
╰────────────────╯
Found 0 target device(s)
[gamer@Zocki ~]$

**Comment by alkazar** [comment]
Sorry, was that output with any controllers connected? Please connect one if not.

**Comment by alkazar** [comment]
Oh, nevermind, I see the controllers now. Inputplumber is not creating any additional virtual controllers. So it doesn't make sense that turning inputplumber off solves your issue...

Also strange that there are some controller devices that don't have a device path. Or is that just the formatting gone wrong?
