### ISSUE TITLE
ONEXPLAYER Mini Pro 6800U - Audio issue while playing games (roaring)

### ISSUE THREAD

**Issue by BluesBrothers7** [ChimeraOS/chimeraos#644]
While playing (e.g. GearClub 2, Sonic - All Star Racing Transformed Collection, etc.) a suddenly a roaring noise appers for around 15 seconds and sometimes it disappers but sometimes it remains constantly.

Hardware:
ONEXPLAYER Mini Pro (AMD - 6800U)

**Comment by jcfrosty** [comment]
This is fixed via device-quirks. This is a common problem with this specific sound card across multiple devices. The fix is to force 16bit audio (S16LE).

Chimera OS v43 will allow you to run frzr-tweaks to apply the audio fix automatically.

**Comment by Samsagax** [comment]
@BluesBrothers7 is your issue fixed by activating tweaks?

**Comment by BluesBrothers7** [comment]
I upgraded to the latest version (unstable) and this issue still exists. Do i have to appy a command in the command line?

**Comment by BluesBrothers7** [comment]
I applyed "frzr-tweaks" as a root user in terminal. After checking for devices-quirks the message "ONE-NETBOOK does not have any supported models. Exiting.". How i can solve this audio roaring problem on my ONEXPLAYER Mini Pro AMD?

**Comment by pastaq** [comment]
It looks like we may have missed one of the DMI strings OnexlXPlayer uses to identify themselves. I can add that, but there's no guarantee the audio fix will be the same so it will need to be tested.
