### ISSUE TITLE
ChimeraOS Won't Shutdown Device When Using Steam Interface

### ISSUE THREAD

**Issue by TheRhysWyrill** [ChimeraOS/chimeraos#806]
As the title explains, when trying to shut down my device using the Steam interface it shuts down Steam correctly but then starts to spit out command lines that end with `shutdown[1]: Powering off.` but the device never does, it requires a forced shutdown, this doesn't occur when shutting down from the desktop side, as a way to "kind of" workaround this issue it seems to shutdown fine the time after a successful desktop mode shutdown.

Below are the command lines I mentioned
![Screenshot 16-11-2023 22-14-30](https://github.com/ChimeraOS/chimeraos/assets/27123572/a6f23866-1f49-4a02-b67f-91708b394726)

**Comment by pastaq** [comment]
What device are you running on?

**Comment by TheRhysWyrill** [comment]
It's a Beelink GTR6 Mini PC, honestly there's been a few strange issues I've run into with this OS and most seems to stem from the use of the Steam Interface in some form, I'm going through all of my options before I make an issue regarding those as it might be something on my end 👍🏻

**Comment by twistedmonkey** [comment]
Second to that, actually @TheRhysWyrill and @pastaq I'm having the same issue with no matter if I use Reboot or shutdown.

My hardware as well is a Beelink SER6 MAX Mini PC, AMD Ryzen 7 7735HS
like in the screenshot it spits out at first some failed mounting issue for the 2 nvme:

[FAILED] Failed to start Mount removable media on nvme1n1p1
[FAILED] Failed to start Mount removable media on nvme0n1p1
[FAILED] Failed to start Mount removable media on nvme1n1p2

and then it goes on and on like in the screenshots to remain stuck forever and I need to hard reset.

I tried chimera 44 and chimera 44-1 same issue

**Comment by a-lyons** [comment]
I'm on a full-size PC with an AMD AMD Ryzen 7 7800X3D and an MSI PRO B650-P motherboard. My shutdown issue is slightly different from @TheRhysWyrill or @twistedmonkey. I'm unable to shutdown from the steam interface or from desktop mode. My computer simply reboots instead of powering off completely.

**Comment by pastaq** [comment]
> I'm on a full-size PC with an AMD AMD Ryzen 7 7800X3D and an MSI PRO B650-P motherboard. My shutdown issue is slightly different from @TheRhysWyrill or @twistedmonkey. I'm unable to shutdown from the steam interface or from desktop mode. My computer simply reboots instead of powering off completely.

Did you enable USB wake for controllers when you installed? You may need to disable that.

**Comment by marc0der** [comment]
I'm on a Lenovo Legion T5 desktop, with Intel i5 and and Radeon RX 6650 XT GPU.

Same issue for me. Shutting down from the Steam UI begins the shutdown process, drops to console, kills the display, but then fails to shut down the power. Suspend shows similar behaviour. However, restarting works fine.

**Comment by Akruidenberg** [comment]
Is this fixed with the latest release?

**Comment by TheRhysWyrill** [comment]
> Is this fixed with the latest release?

I don't believe so, I've been on the testing builds for a while now and it still occurring for me there.

**Comment by Akruidenberg** [comment]
@TheRhysWyrill Thanks!

**Comment by TheRhysWyrill** [comment]
@pastaq Here you are, hopefully this points towards the cause 👍🏻

[journalctl.log](https://github.com/ChimeraOS/chimeraos/files/14671279/journalctl.log)

**Comment by Akruidenberg** [comment]
Installed the latest version of chimeraos. Problem is fixed for me.

**Comment by megamaced** [comment]
Issue is still present on v46 and Ayaneo Pro 2021

**Comment by yhilg** [comment]
I had similar problems; my device kept booting up instead of ever completely shutting down.

A software update released today fixed that for me.

You might wish to resume where you had left off.

xo
