### ISSUE TITLE
Duplicated controller  - strange controller  behavior

### ISSUE THREAD

**Issue by thekk1** [ChimeraOS/chimeraos#980]
All controllers appear twice. Bluetooth section shows 1, but controller sections shows 2 controllers.
With 2 Controllers there are 4 showed in controller section.
Tested with multiple DS4 Controller.

If there are 2 or more controllers connected and you playing a game, after some while the first (blue) controller got issues and does not accept all button inputs then it got disconnected. It's like the BT signal has problems.
Reconnecting the controller needs multiple tries and the controller is not functional and got disconnected after a while again.
This happens always and only with the first connected controller with blue lights and while a game is playing. Changing the series of connecting the controllers, so an other controller is the first (blue) one, it happens to this controller.
Tested with Mortal Kombat 11, TMNT Shredders Revenge and Horizon Chase Turbo

After a full restart of the system, it's working again for a short time (~30 sec) and then happens again.

Setup:
minisforum um790 pro
4x DS4 controller
Plain ChimeraOS 45-1

**Comment by thekk1** [comment]
Because there seems to be no fix or help and part of this issue are month old, I decided to follow this solution:
https://github.com/ChimeraOS/chimeraos/issues/918

**Comment by alkazar** [comment]
Can you update to ChimeraOS 46 and confirm that this is fixed?

**Comment by thekk1** [comment]
I am sorry but I can't.
As I said I followed the solution in #918 and switched to bazzite.

**Comment by alkazar** [comment]
Alright, thanks. The issue is fixed as far as I can tell.

**Comment by 200Puls** [comment]
Hi @alkazar,

I still have the same issue.
And it has gotten worse.
Im using mainly 3 Dualsense Controllers. Sometimes Input on the Steam profile selection is  not registered at all.
And often I have dual devices in games. 
Using Version 46-1

**Comment by pastaq** [comment]
@200Puls thank you, I'll reopen and investigate

**Comment by 200Puls** [comment]
@pastaq 
Thanks for reopening.
I just updated to 46-2 and the not working input seems to be fixed.
I will try to replicate the duplicate input tomorrow.

**Comment by 200Puls** [comment]
@pastaq 
I extensively tested it now. The problems I still Encounter are:

* when I Turn Off a connected Dualsense Controller and I turn it back on: No input is received. With the Steam Controller and Xbox this works
* When I Connect 3 Dualsense Controllers I have Phantom input errors where one of the Controllers acts as two. This is in the Steam Interface as well as in games like Sonic cart. Using two Dualsense and one Xbox controller does Not cause this issue.

**Comment by 200Puls** [comment]
@pastaq both issues are fixed for me If I disable the inputplumber service as suggested in the linked issue.

Is there any reason why I should not disable it?

**Comment by pastaq** [comment]
InputPlumber is our input management software, think of it like open source steam input. It is only strictly necessary if either your controller doesn't work by default/has missing features (most handhelds) or if you want to use the steam-plus or opengamepadui sessions.

**Comment by thekk1** [comment]
I can confirm that the Problem with double controller is fixed on 46-2.

**Comment by thekk1** [comment]
Both problems seemed to be solved at 46-2.
